
services:
  gitsync:
    image: registry.k8s.io/git-sync/git-sync:v4.1.0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./sync:/workspace

  backend:
    build:
      context: .
    container_name: birdsong-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - gitsync
    volumes:
     - ./config.yaml:/etc/birdsong/config.yaml
      - ./sync:/workspace
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    ports:
      - "${API_PORT:-8000}:8000"
    command: >
      /bin/sh -c 'exec uvicorn api:app --host 0.0.0.0 --port 8000 --reload --reload-dir /workspace'
