
services:
  api:
    image: birdsong-be:0.0.1 
    container_name: birdsong-api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.yaml:/etc/birdsong/config.yaml:ro
      - ./birdsong-backend/app:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./models:/app/models
    ports:
      - "${API_PORT:-8000}:8000"
    command: >
      /bin/sh -c 'exec uvicorn api:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app'

  

  analyzer:
    image: birdsong-be:0.0.1 
    container_name: birdsong-analyzer
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.yaml:/etc/birdsong/config.yaml:ro
      - ./birdsong-backend/app:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./models:/app/models
    command: >
      /bin/sh -c 'python main.py'
